### ISSUE TITLE
folder history has most recent folder at the bottom

### ISSUE THREAD

**Issue by Olifair** [alainfrisch/nostalgy#29]
Hello, 
first, a great thanks for this plugin. I just switched recently to Thunderbird, and this is probably the most helpful plugin I installed, saves me a lot of time. 
It would probably save me still more time if the folder history that it shown after hitting the g/s/c keys could be inverted : in the moment, the most recent folder is at the bottom of the list, so I need to hit the down arrow several times to reach it, however it is the most likely to be used, Whereas the oldest folder int he list (least used) is on the top. 
Thanks for considering this (perhaps as an option ?)

Cheers

Oliver

**Comment by alainfrisch** [comment]
Doesn't pressing "up" instead of "down" do what you want?

**Comment by Olifair** [comment]
Ok, yes, you are right !! As the list is below the text box, I probably supposed that I would need to go down. But up is getting me to the last item. 
Thanks for your response to this rather obvious point

Cheers

Oliver

**Comment by alainfrisch** [comment]
You're welcome!
