### ISSUE TITLE
List of keyboard shortcuts available?

### ISSUE THREAD

**Issue by karinlag** [alainfrisch/nostalgy#36]
I really like this one, but there seems to be more than 3 shortcuts available. Is there a list somewhere?

Thanks!

**Comment by hi5** [comment]
Here is the old(er) documentation with a short list http://alain.frisch.fr/info/ABOUT_NOSTALGY.html - but you can setup more keys in the Nostalgy preferences. Hope this is useful.

**Comment by karinlag** [comment]
Thanks, this helps a lot!
