### ISSUE TITLE
Compatibility with Thunderbird 57?

### ISSUE THREAD

**Issue by gwhitney** [alainfrisch/nostalgy#39]
My Thunderbird just updated to version 57beta1 (I have generally been running on the beta release channel) and Nostalgy seems to have stopped working. Can anyone verify whether or not Nostalgy should work with Thunderbird 57? If it is not currently working with Thunderbird 57, what are the prospects for it being enhanced to work with that version?  Thanks so much, it is a *wonderful* add-on.

**Comment by jmozmoz** [comment]
There exists already a patch, which looks like fixing this problem: 
https://github.com/oeekker/nostalgy/commit/9d1ddfebeb8186f25d98134d6c6b54cec7e1cdbd

**Comment by gwhitney** [comment]
Nostalgy 0.2.35 fixed this compatibility problem, but it has struck again with Thunderbird 60, so I opened #46 for that; closing this one.
