### ISSUE TITLE
Create new folder in any folder

### ISSUE THREAD

**Issue by caugner** [alainfrisch/nostalgy#43]
**Background**: When moving a message, Nostalgy allows creating a new folder on the go (when no folder was found matching the query).

**Problem**: The new folder is always created under the current folder.

**Feature request**: When creating a new folder, Nostalgy should prompt "Create new folder under:" with the current folder being the default, but allowing to search and select any folder.

**Comment by caugner** [comment]
As far as I can see, the right place to insert the feature would be here:

https://github.com/alainfrisch/nostalgy/blob/5bc92187b38a2eb6d33f42b73bd72dd021b90488/content/nostalgy.js#L380-L410

**Comment by JoelAzaria** [comment]
ime if you just type the path (in the 'save' box) to the 'parent' folder you want to create in then append '/newfoldername' nostalgy WILL create it in the right place.

The related problem _I've_ run into is that nostalgy *creates* the folder but doesn't save the messages there.  For that you have to repeat the move command a second time.

Can you confirm?

**Comment by caugner** [comment]
> ime if you just type the path (in the 'save' box) to the 'parent' folder you want to create in then append '/newfoldername' nostalgy WILL create it in the right place.

@JoelAzaria Yes, you're right. I have actually discovered that feature meanwhile …

> The related problem I've run into is that nostalgy creates the folder but doesn't save the messages there. For that you have to repeat the move command a second time.

… but experience the same problem from time to time.

I'm closing this issue anyway, because the feature is already there. :tada:
