### ISSUE TITLE
's' conflicts with TB's "add/remove Star" shortcut - remap?

### ISSUE THREAD

**Issue by jmtd** [alainfrisch/nostalgy#49]
Hi, I love nostalgy!

"S" makes a lot of sense for the purpose that Nostalgy uses it, but it does clash with TB's normal behaviour of "add star" (or unstar) i.e. flag as important. Since such flags are saved over IMAP (and tags are not), it can be important to use stars 

It'd be great if Nostalgy could either offer another shortcut for the old behaviour, or offer a way of configuring an alternative hot key.

One way outside of Nostalgy that this can be achieved is with this extension which seems to work https://addons.mozilla.org/en-US/thunderbird/addon/dorando-keyconfig/?src=userprofile

**Comment by alainfrisch** [comment]
Nostalgy configuration popup has a tab "Keys", where you can override the default bindings for Nostalgy actions.  Does that work for you?

**Comment by jmtd** [comment]
> Nostalgy configuration popup has a tab "Keys", where you can override the default bindings for Nostalgy actions. Does that work for you?

Not exactly, because I'd rather leave 'S' assigned to nostalgy, but it's useful to know anyway, thanks!

**Comment by JoelAzaria** [comment]
Actually Tbird's default binding for flag/unflag iirc is 'i' not 's' and has been as long as I can remember.  Are you using a localized version?

Also, yes just use Keyconfig and map everything.
@alainfrisch  I think this issue should be closed.

**Comment by jmtd** [comment]
> Actually Tbird's default binding for flag/unflag iirc is 'i' not 's' and has been as long as I can remember. Are you using a localized version?

en_GB

> @alainfrisch I think this issue should be closed.

No objections from me - I'll do it.
