### ISSUE TITLE
Thunderbird 60.0

### ISSUE THREAD

**Issue by klausatlas** [alainfrisch/nostalgy#52]
Hi,

nostalgy is a great extension but it stopped working with thunderbird 60. Will it be updated?

**Comment by caugner** [comment]
It looks like @alainfrisch is actively working on this, see [this commit](https://github.com/alainfrisch/nostalgy/commit/e6b1084f966ecb4e9e6ec62a7192ced760e9c87c). 🎉

**Comment by alainfrisch** [comment]
Duplicate of #46.
