### ISSUE TITLE
FR: delete attachments from multiple messages

### ISSUE THREAD

**Issue by chconnor** [alainfrisch/nostalgy#99]
Hi -- I just wanted to leave a potentially strange feature request:

There is currently no way to mass delete attachments from more than one message. E.g. if you have 4000 messages in a folder with attachments and your ESP is near-quota, you have to manually delete them one by one (there actually are some options -- see my blog post linked below -- but they aren't perfect.)

There used to be TB extensions to do this, but they are no more, so I recently had to write a python script to log in to my mail server to do this automatically.

So, personally, I don't need the feature, but if you were looking for something that would be unique to Nostalgy and _really_ useful for the people that are looking for it (and possibly not that hard to implement in an extension?) then I thought you might consider it.

Here's my blog post on the subject, in case it's of use: http://lacinato.com/cm/blog/27-imapsizereducer

**Comment by hi5** [comment]
@chconnor you might have better luck posting it in the nostalgy++ repository as that is the TB78 compatible successor of Nostalgy in active development by opto: https://github.com/opto/nostalgy-xpi

**Comment by chconnor** [comment]
D'oh, I thought I was, sorry. :-)
